Update dependencies.md
Because when you whant enable extension :

 sudo -u postgres psql -c "CREATE EXTENSION pg_trgm;" peertube_prod
ERROR:  could not open extension control file "/usr/local/share/postgresql/extension/pg_trgm.control": No such file or directory

pkg install postgresql96-contrib

-> and its ok
(Note : i use a presonal repository whith poudriere, maybe in the offical repository postgresql96-contrib depends on  postgresql96-server )